# server
server:
  port: 8082

# upload path @AuthController /upload
me:
  upload:
    path: E:/cocuFile/
jwt:
  secret: COCU_RYAN
spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cocu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  #static
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${me.upload.path}
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${me.upload.path}
  #spring.mvc.static-path-pattern=/**
  #spring.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,\
  #classpath:/static/,classpath:/public/,file:${me.upload.path}


  servlet:
    # file upload
    multipart:
      # max file size of single upload
      max-file-size: 20MB
      # max file size of a single HTTP request
      max-request-size: 20MB

  # send email
#  mail:
#    host: smtp.qq.com
#    username: 1342502141@qq.com
#    #Enter the following authorization code in the password input box when you log in with a third-party client.
#    #authorization code: xvmbtrcymippjjhi
#    password: xvmbtrcymippjjhi
#    from: 1342502141@qq.com
#    protocol: smtp
#    port: 465
#    default-encoding: UTF-8
#    properties:
#      "mail.smtp.ssl.enable": true
  mail:
    host: smtp.qq.com  # qq的邮件服务器主机地址 【163网易邮箱的是smtp.163.com】
    username: 1342502141@qq.com  # 登录邮件服务器的邮箱【自己的邮箱】
    # mtppgatzlhkfbabd
    password: mtppgatzlhkfbabd  # 授权码
    port: 587  # 邮件服务器端口号  【163网易邮箱的是465】
    smtp:
      from: 1342502141@qq.com
      auth: true  # 是否需要身份验证
      starttls.enabled: true  # 是否启用 STARTTLS 支持
    default-encoding: utf-8  # 默认邮件编码为 UTF-8




  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false

# mybatis-plus
mybatis-plus:
  configuration:
    # log
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # logical delete field
      logic-delete-field: delFlag
      # represent delete
      logic-delete-value: 1
      # represent not delete
      logic-not-delete-value: 0
      # primary key auto increment
      id-type: auto





# cocu_comment,cocu_notification,cocu_user_like,cocu_user_star
